import { useState, useEffect } from 'preact/hooks';
import { api, config, navigate, errorToast, typeIcon, toast } from '../lib.js';
import { useSignal } from '../signal.js';
import { Loading, Empty } from '../ui.jsx';

export default function Ask({ query }) {
  const cfg = useSignal(config);
  const [q, setQ] = useState(query.q || '');
  const [mode, setMode] = useState(query.mode || 'hybrid');
  const [res, setRes] = useState(null);
  const [busy, setBusy] = useState(false);
  const run = async (question = q) => {
    if (!question.trim()) return;
    setBusy(true);
    try { setRes(await api.post('/graphrag/query', { query: question, mode, answer: !!cfg.llm })); }
    catch (e) { errorToast(e); } finally { setBusy(false); }
  };
  useEffect(() => { if (query.q) run(query.q); }, []);
  return (
    <div class="narrow wide ask">
      <h1>✨ Ask the knowledge base</h1>
      <p class="muted">GraphRAG retrieval: combines keyword and semantic search with the knowledge graph (links, typed relations, tags) and topic clusters.
        {cfg.llm ? ' Answers are written by the configured AI model and cite their sources.' : ' Connect an AI model in Admin › Settings to get written answers; retrieved sources are shown either way.'}</p>
      <form class="search-form" onSubmit={(e) => { e.preventDefault(); navigate(`/ask?q=${encodeURIComponent(q)}`, { replace: true }); run(); }}>
        <input value={q} onInput={(e) => setQ(e.target.value)} placeholder="e.g. Who owns the billing service and what does it depend on?" aria-label="Question" autoFocus />
        <select value={mode} onChange={(e) => setMode(e.target.value)} aria-label="Retrieval mode">
          <option value="hybrid">Hybrid (recommended)</option><option value="local">Local — entity-centric</option><option value="global">Global — themes & clusters</option><option value="vector">Semantic only</option>
        </select>
        <button class="btn primary" disabled={busy}>{busy ? 'Thinking…' : 'Ask'}</button>
      </form>
      {busy && <Loading label="Retrieving knowledge…" />}
      {res && !busy && <div class="ask-results">
        {res.answer && <section class="card answer"><h2>Answer</h2><div class="answer-text">{res.answer.split('\n').map(l => <p>{l.split(/(\[\d+\])/).map(part => { const m = /^\[(\d+)\]$/.exec(part); const c = m && res.chunks[+m[1] - 1]; return c ? <a class="cite" href={c.url} title={c.heading}>{part}</a> : part; })}</p>)}</div>
          <small class="muted">Generated by {res.model}. Verify important facts in the cited pages.</small></section>}
        {res.error && <div class="banner warn">{res.error}</div>}
        <section class="card"><h2>Sources <small class="muted">{res.chunks.length} passages · {res.ms} ms · mode {res.mode}</small></h2>
          {res.chunks.length ? <ol class="sources">{res.chunks.map(c => <li><a href={c.url}>{typeIcon(c.type)} {c.heading}</a> <small class="muted">{c.space} · score {c.score}</small><p>{c.text.slice(0, 400)}{c.text.length > 400 ? '…' : ''}</p></li>)}</ol>
            : <Empty>Nothing relevant found. Try rephrasing, or <a href={`/search?q=${encodeURIComponent(q)}`}>search</a>.</Empty>}
        </section>
        <div class="two-col">
          {res.entities.length > 0 && <section class="card"><h2>Entities</h2><ul class="entities">{res.entities.map(e => <li>{e.kind === 'page' ? <a href={`/p/${e.pageId}`}>{typeIcon(e.type)} {e.label}</a> : e.kind === 'tag' ? <a href={`/tags/${encodeURIComponent(e.label.slice(1))}`}>{e.label}</a> : e.label} <small class="muted">{e.kind}{e.seed ? ' · in question' : ''}</small></li>)}</ul></section>}
          {res.relations.length > 0 && <section class="card"><h2>Relations</h2><ul class="relations">{res.relations.slice(0, 25).map(r => <li>{r.source} <span class="rel">—{r.rel}→</span> {r.target}</li>)}</ul></section>}
        </div>
        {res.communities.length > 0 && <section class="card"><h2>Related topic clusters</h2><ul>{res.communities.map(c => <li><strong>{c.title}</strong> <small class="muted">({c.size} nodes)</small><div class="muted small">{c.summary}</div></li>)}</ul></section>}
        <details class="card"><summary>Use this from other systems</summary>
          <p>The same retrieval is available to other tools and AI agents:</p>
          <pre><code>{`curl -H "Authorization: Bearer <token>" \\\n  "${location.origin}/api/v1/graphrag/query?q=${encodeURIComponent(res.query)}&mode=${res.mode}"`}</code></pre>
          <p>MCP endpoint for AI agents: <code>{location.origin}/mcp</code> (tools: search, graphrag_query, get_page, get_neighbors, get_ontology…)</p>
          <button class="btn small" onClick={() => { navigator.clipboard && navigator.clipboard.writeText(res.context); toast('LLM context copied', 'success'); }}>Copy LLM-ready context</button>
        </details>
      </div>}
    </div>
  );
}
